library(seqinr)
source("http://bioconductor.org/biocLite.R")
biocLite()
library(BiocInstaller)
biocVersion()
biocValid()
biocLite(c("GenomicRanges","biomaRt", "AnnotationDbi" ))
biocLite("Biostrings")
biocLite("BSgenome.Ecoli.NCBI.20080805")
library(GenomicRanges)
library(biomaRt)
library(BSgenome.Ecoli.NCBI.20080805)
#help("useMart")
#mart=useMart("ensembl")
#listDatasets(mart)
#Importing ecoli genome to test
ecl<-Ecoli$NC_008563
#counting nucleotides (this one counts AAs as well)
alphabetFrequency(ecl)
#counting only nucleotides
letterFrequency(ecl, letters = "ACGT", OR=0)
